# config.toml

[minecraft]
admins = ["Loopking", "BT1013", "jc_cr"]
log_path = "/mc-data/logs/latest.log"

[aipm]
# list of mc username of team members for AIPM team
members = ["jc_cr"]

[aipm.planner_agent]
# Prompt with: map layout, player locations, round structures list, structure recipes for round
start_of_round_prompt = """
You must plan the building strategy for the team.
"""

# Milestone update prompt: previous plan, map layout, player locations, player inventory, remaining structures, structure recipes
milestone_prompt = """
Update the plan based on current progress and team status.
"""

[aipm.manager_agent]