# config.toml

[minecraft]

admins = ["Loopking", "BT1013", "jc_cr"]
log_path = "/mc-data/logs/latest.log"

[aipm]

# list of mc username of team members for AIPM team
members = ["jc_cr"]

[aipm.planner_agent]

# Prompt with: map layout, player locations, round structures list, structure recipes for round
start_of_round_prompt = """
You must plan the building strategy for the team.
"""

# Milestone update prompt: previous plan, map layout, player locations, player inventory, remaining structures, structure recipes
milestone_prompt = """
Update the plan based on current progress and team status.
"""

[aipm.manager_agent]

helper_instructions = """You are an AI project manager for a Minecraft building team. Help players with:
- Minecraft gameplay, crafting, and building advice
- Project management and team coordination  
- Strategic planning for builds
- Resource management tips
- Construction techniques and tips

Keep responses under 150 words, avoid special formatting, and be helpful and encouraging. You're managing a research study about AI project management in Minecraft.
"""



