#File: .docker/docker-compose.yml
services:
  py-base:
    build:
      context: .
      dockerfile: Dockerfile.python
    user: "${UID:-1000}:${GID:-1000}"
    env_file: .env
    ports:
      - "5000:5000"

  logs_to_db:
    extends: py-base
    volumes:
      - /root/ai-pm-mc-world-dev/minecraft-dev/logs/latest.log:/app/data/latest.log:ro
      - ../data:/app/data/db
      - ../ai-pm:/app/scripts
    command: bash -c "python3 /app/scripts/logs_to_db.py"

  hello_mcron:
    extends: py-base
    volumes:
      - ../ai-pm:/app/scripts
      - /root/ai-pm-mc-world-dev/minecraft-dev/:/mc-data:ro
    command: bash -c "python3 /app/scripts/hello_mcron.py"


  minecraft:
    image: itzg/minecraft-server:latest
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      MEMORY: "2G"
      DIFFICULTY: "peaceful"
      MODE: "creative"
      MAX_PLAYERS: 20
      ONLINE_MODE: "true"
      WHITE_LIST: "false"
      ENABLE_COMMAND_BLOCK: "true"
      LEVEL_TYPE: "flat"
      OPS: "Loopking,BT1013,jc_cr"
    ports:
      - "25565:25565"
    volumes:
      - ../minecraft-dev:/data
    restart: unless-stopped

  latex:
      user: "${UID:-1000}:${GID:-1000}"
      build:
        context: ..
        dockerfile: .docker/Dockerfile.latex 
      ports:
        - "3000:3000"  # For LaTeX Workshop
      working_dir: /project
      command: tail -f /dev/null
      volumes:
       - ../paper/src:/project/src
       - ../paper/output:/project/output
       - ../paper/figures:/project/figures
       - ../paper/include:/project/include

