#File: .docker/docker-compose.yml
services:
  
  # Python base for shared image
  py-base:
    build:
      context: .
      dockerfile: Dockerfile.python
    user: "${UID:-1000}:${GID:-1000}"

  # Listens to minecraft events and generates an appropiate response
  figures:
    extends: py-base
    volumes:
      - ../scripts:/app/scripts
    command: bash -c "python3 /app/scripts/figures.py"


  infer:
    extends: py-base
    volumes:
      - ../scripts:/app/scripts
    command: bash -c "python3 /app/scripts/infer.py"

  check:
    extends: py-base
    volumes:
      - ../scripts:/app/scripts
    command: bash -c "python3 /app/scripts/linear_check.py"